Fix N+1 queries when fetching premises availability
ministryofjustice/hmpps-approved-premises-api pull request #1208
Opened 2023-12-05 14:15 UTC by pezholio

When checking out [some of the endpoints that had N+1 queries via Application Insights](https://portal.azure.com/#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA1WOSw7CMAxE95zCYlOKVAEH6Io9Cy5QhWYEkZraJE6hiMOTgvjtrHnzRrYQ9BZ96xBnd7qcEEBtx8k2e%252B6wMx5U11QYkcADbCUB3kXEyogr6KPoKM%252FiXDjqMSCeu3mGuGqeJ2U1XWNTMOq4r9%252FH0in8llOvuRqT9ya4G8gMx293kfPFv1%252BupuzjliUdRmLBizbTz3lPWWizntDvHlnE9gGhmpMD9QAAAA%253D%253D/timespan/P1D) I noticed that the `premisesPremisesIdSummaryGet` endpoint was making a lot of queries (sometimes upwards of 700!). Digging into it it seems that when we fetch bookings when calculating the availability for a premises, we're querying for each booking's cancellations, arrivals and departures, thus ending up in an N+1 query situation.

This updates one of our queries to use JPA projection to only fetch counts of cancellations, arrivals and departures, which should cut down on the number of queries made and speed up the response from this endpoint.

2023-12-05 15:00 UTC, davidatkinsuk requested changes
For approval can we please add an integration test for the new native query?

2023-12-05 17:16 UTC, pezholio commented on src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt
> +  @Query("SELECT lb FROM LostBedsEntity lb left join lb.cancellation cancellation WHERE lb.premises.id = :premisesId AND lb.startDate <= :endDate AND lb.endDate >= :startDate")
Oh, you're right I think. I'll remove this commit.

2023-12-06 08:33 UTC, pezholio commented on src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
> +  @Query(
Good call 👍

2023-12-06 10:23 UTC, davidatkinsuk commented
LGTM

2023-12-06 10:23 UTC, davidatkinsuk approved these changes
LGTM

2023-12-06 10:28 UTC, merged