[APS-751] Fix applications getting stuck in the 'further information requested' state when a decision is made while a clarification note is pending
ministryofjustice/hmpps-approved-premises-api pull request #1886
Opened 2024-05-15 14:08 UTC by danlivings-dxw

> See [APS-751 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-751).

This PR fixes the bug introduced in #1805 which prevents any state transition when the current state is `REQUESTED_FURTHER_INFORMATION`. This prevents an update to the assessment from changing the status, but also prevents a decision being made changing the status, which is incorrect.

A test has been introduced that verifies the expected behaviour as outlined in #1805 to make sure that this change does not cause the original bug to reappear.

Additionally, a Flyway migration has been added to update any applications that have been affected by this bug.

2024-05-20 14:27 UTC, davidatkinsuk requested changes
Sorry, I've just spotted something:

```
UPDATE approved_premises_applications
SET status = 'PENDING_PLACEMENT_REQUEST'
WHERE id IN (
    SELECT application_id
    FROM assessments
    WHERE decision = 'ACCEPTED'
    AND reallocated_at IS NULL
)
AND status = 'REQUESTED_FURTHER_INFORMATION';
```

I don't think this is going to be correct in all cases as the application's may have progressed further than PENDING_PLACEMENT_REQUEST. Without writing more SQL I wonder if a migration job would be better placed to 'fix' these applications that can re-use the logic in the AssessmentListener?

In the meantime we could remove this migration and at least get this PR merged as to reduce the number of assessments affected?

2024-05-20 16:14 UTC, edavey approved these changes
Nice work, this looks clear and correct. I've made a couple of minor comments.

2024-05-21 07:16 UTC, davidatkinsuk commented on src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
> +AND status = 'REQUESTED_FURTHER_INFORMATION';
@edavey did you see my comment re: "I don't think this is going to be correct in all cases as the application's may have progressed further than PENDING_PLACEMENT_REQUEST". I'm happy to be proven incorrect on this! Maybe applications can't be any further as they're currently stuck?

2024-05-21 08:12 UTC, edavey commented on src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
> +AND status = 'REQUESTED_FURTHER_INFORMATION';
yes, thanks for this. I've had a little dig and yes of the 31 cases where the assessment was accepted:

- 14 applications have placement applications of which 4 of those placement applications have been accepted
- 10 applications have a total of 24 bookings

2024-05-21 15:13 UTC, danlivings-dxw commented on src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
> +AND status = 'REQUESTED_FURTHER_INFORMATION';
I don't think that would be the case as each query has `AND status = 'REQUESTED_FURTHER_INFORMATION'` as a condition, meaning that it if it's changed in an earlier query it wouldn't then be eligible for the update in the later ones.

2024-05-21 15:29 UTC, edavey commented on src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
> +AND status = 'REQUESTED_FURTHER_INFORMATION';
👍 let's test out on pre-prod!

2024-05-21 15:32 UTC, edavey approved these changes

2024-05-21 15:36 UTC, edavey commented on src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
> +AND status = 'REQUESTED_FURTHER_INFORMATION';
I've run the migration query on pre-prod and confirmed that it behaves as desired.

2024-05-22 07:05 UTC, davidatkinsuk approved these changes
Thanks for the effort from you both to get these migrations refined. LGTM.

FYI - i've captured a list of application ids affected by the migrations on the ticket for reference just in case there are any issues (I don't think there will be, but no harm in capturing them) 👍

2024-05-22 09:12 UTC, merged